services:
  app:
    build: .
    container_name: camisas-chinesas-backend
    ports:
      - "3333:3333"
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: postgres:16.9-bullseye
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: playground
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: